export interface Employeemodel {
    employee_code:string,
    first_name:string,
    last_name:string,
    date_of_birth:Date,
    gender:string,
    phone_no:string,
    alternate_phone_no:string,
    email:string,
    user_type:string,
    //image:string,
    academic_id:1,
    institution_id:1,
    designation_id :Number,
    joining_date:Date,
    qualification:string,
    experience:string,
    departmant_id:Number,
    blood_group_id:string,
    present_address :string,
    perminent_address:string,
    state_id:string,
    city :string,
    pin_code:string
}
