export interface Student {
academic_id:number
institution_id:number
present_address:string
perminent_address:string
state:string
city:string
pin_code:string
admission_number:number
admission_date:Date
first_name:string
last_name:string
date_of_birth:Date
gender:string
mobile_no:string
alternate_mobile_no:string
email:string
student_roll_no:string
nationality:string
father_name:string
father_mobile_no:string
father_designation:string
mather_name:string
mother_mobile_no:string
mother_designation:string
guardian_name:string
guardian_mobile_no:string
guardian_second_mobile_no:string
guardian_address:string
guardian_email:string
relation:string
guardian_designation:string
blood_group_id:number
religion_id:number
cast_id:number
mother_tongue_id:number
class_id:number


}
